# Generated by Django 5.2.8 on 2025-11-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_support_level_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('schedule', 'Изменение расписания'), ('api_issue', 'Проблема с API'), ('notification', 'Не понимаю уведомление'), ('system_performance', 'Система работает медленно'), ('response_time', 'Медленный ответ техподдержки'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
